_convert_dict:
    value: true
_fields:
    value:
        model: |
            hidden_size: 500
            input_size: 784
            name: neural_net
            num_classes: 10
        project_name: my_model_project
        run_name: experiment_1
        training: |
            batch_size: 100
            dataset: MNIST
            learning_rate: 0.001
            num_epochs: 2
_locked:
    value: false
_type_safe:
    value: true
_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
